@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.company.Boton#mostrar()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.company.Boton",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_950484093 { 
   	label=company
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_155329796 { 
   	label=Cliente
	labeljust=l
	fillcolor=white
	style=filled
   
   Cliente2071347952XXXmostrar0[
	label="+ mostrar()"
	style=filled
	fillcolor=white
	tooltip="Cliente

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1963288543 { 
   	label=Demo
	labeljust=l
	fillcolor=white
	style=filled
   
   Demo2071347952XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Demo

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2033366758 { 
   	label=DialogoWindows
	labeljust=l
	fillcolor=white
	style=filled
   
   DialogoWindows2071347952XXXmostrar0[
	label="+ mostrar()"
	style=filled
	fillcolor=white
	tooltip="DialogoWindows

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_57683814 { 
   	label=DialogoMac
	labeljust=l
	fillcolor=white
	style=filled
   
   DialogoMac2071347952XXXmostrar0[
	label="+ mostrar()"
	style=filled
	fillcolor=white
	tooltip="DialogoMac

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_733944984 { 
   	label=Boton
	labeljust=l
	fillcolor=white
	style=filled
   
   Boton2071347952XXXmostrar0[
	label="+ mostrar()"
	style=filled
	fillcolor=white
	tooltip="Boton

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

'edges    
Boton2071347952XXXmostrar0 -> DialogoMac2071347952XXXmostrar0;
Boton2071347952XXXmostrar0 -> DialogoWindows2071347952XXXmostrar0;
Cliente2071347952XXXmostrar0 -> Boton2071347952XXXmostrar0;
Demo2071347952XXXmain1859653459 -> Cliente2071347952XXXmostrar0;
    
}
@enduml